// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Context;

#nullable disable

namespace Project.Migrations
{
    [DbContext(typeof(MasterContext))]
    [Migration("20250517152201_Inital")]
    partial class Inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Project.Models.AudioLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaTitle");

                    b.ToTable("AudioLanguages");
                });

            modelBuilder.Entity("Project.Models.AudioOption", b =>
                {
                    b.Property<string>("MediaTitle")
                        .HasColumnType("TEXT");

                    b.HasKey("MediaTitle");

                    b.ToTable("AudioOptions");
                });

            modelBuilder.Entity("Project.Models.MediaContent", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("AudioOptionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalLanguage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterImage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime");

                    b.Property<int>("SubtitleOptionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrailerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Title");

                    b.HasIndex("OriginalLanguage");

                    b.HasIndex("ReleaseDate");

                    b.ToTable("MediaContents");

                    b.HasDiscriminator().HasValue("MediaContent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Project.Models.MediaContentStreamingService", b =>
                {
                    b.Property<string>("MediaTitle")
                        .HasColumnType("TEXT");

                    b.Property<int>("StreamingServiceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaTitle", "StreamingServiceId");

                    b.HasIndex("StreamingServiceId");

                    b.ToTable("MediaContentStreamingServices");
                });

            modelBuilder.Entity("Project.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaTitle");

                    b.HasIndex("UserId", "MediaTitle");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Project.Models.StreamingService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaContentTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaContentTitle");

                    b.ToTable("StreamingServices");
                });

            modelBuilder.Entity("Project.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DefaultPrice")
                        .HasColumnType("REAL");

                    b.Property<int>("StreamingServiceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StreamingServiceId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Project.Models.SubscriptionConfirmation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("SubscriptionConfirmations");
                });

            modelBuilder.Entity("Project.Models.SubtitleLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaTitle");

                    b.ToTable("SubtitleLanguages");
                });

            modelBuilder.Entity("Project.Models.SubtitleOption", b =>
                {
                    b.Property<string>("MediaTitle")
                        .HasColumnType("TEXT");

                    b.HasKey("MediaTitle");

                    b.ToTable("SubtitleOptions");
                });

            modelBuilder.Entity("Project.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Firstname")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Project.Models.WatchHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeLeftOf")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("WatchDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("MediaTitle");

                    b.HasIndex("TimeLeftOf");

                    b.ToTable("WatchHistories");
                });

            modelBuilder.Entity("Project.Models.Documentary", b =>
                {
                    b.HasBaseType("Project.Models.MediaContent");

                    b.Property<string>("Topics")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Documentary");
                });

            modelBuilder.Entity("Project.Models.Movie", b =>
                {
                    b.HasBaseType("Project.Models.MediaContent");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Movie");
                });

            modelBuilder.Entity("Project.Models.AudioLanguage", b =>
                {
                    b.HasOne("Project.Models.AudioOption", "AudioOption")
                        .WithMany("AudioLanguages")
                        .HasForeignKey("MediaTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AudioOption");
                });

            modelBuilder.Entity("Project.Models.AudioOption", b =>
                {
                    b.HasOne("Project.Models.MediaContent", "MediaContent")
                        .WithOne("AudioOption")
                        .HasForeignKey("Project.Models.AudioOption", "MediaTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaContent");
                });

            modelBuilder.Entity("Project.Models.MediaContentStreamingService", b =>
                {
                    b.HasOne("Project.Models.MediaContent", "MediaContent")
                        .WithMany("MediaContentStreamingServices")
                        .HasForeignKey("MediaTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.StreamingService", "StreamingService")
                        .WithMany("MediaContentStreamingServices")
                        .HasForeignKey("StreamingServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaContent");

                    b.Navigation("StreamingService");
                });

            modelBuilder.Entity("Project.Models.Review", b =>
                {
                    b.HasOne("Project.Models.MediaContent", "MediaContent")
                        .WithMany("Reviews")
                        .HasForeignKey("MediaTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.WatchHistory", "WatchHistory")
                        .WithMany()
                        .HasForeignKey("UserId", "MediaTitle")
                        .HasPrincipalKey("UserId", "MediaTitle")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MediaContent");

                    b.Navigation("User");

                    b.Navigation("WatchHistory");
                });

            modelBuilder.Entity("Project.Models.StreamingService", b =>
                {
                    b.HasOne("Project.Models.MediaContent", null)
                        .WithMany("StreamingServices")
                        .HasForeignKey("MediaContentTitle");
                });

            modelBuilder.Entity("Project.Models.Subscription", b =>
                {
                    b.HasOne("Project.Models.StreamingService", "StreamingService")
                        .WithMany("Subscriptions")
                        .HasForeignKey("StreamingServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StreamingService");
                });

            modelBuilder.Entity("Project.Models.SubscriptionConfirmation", b =>
                {
                    b.HasOne("Project.Models.Subscription", "Subscription")
                        .WithMany("Confirmations")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.User", "User")
                        .WithMany("Confirmations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Models.SubtitleLanguage", b =>
                {
                    b.HasOne("Project.Models.SubtitleOption", "SubtitleOption")
                        .WithMany("SubtitleLanguages")
                        .HasForeignKey("MediaTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubtitleOption");
                });

            modelBuilder.Entity("Project.Models.SubtitleOption", b =>
                {
                    b.HasOne("Project.Models.MediaContent", "MediaContent")
                        .WithOne("SubtitleOption")
                        .HasForeignKey("Project.Models.SubtitleOption", "MediaTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaContent");
                });

            modelBuilder.Entity("Project.Models.WatchHistory", b =>
                {
                    b.HasOne("Project.Models.MediaContent", "MediaContent")
                        .WithMany("WatchHistories")
                        .HasForeignKey("MediaTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.User", "User")
                        .WithMany("WatchHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaContent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Models.AudioOption", b =>
                {
                    b.Navigation("AudioLanguages");
                });

            modelBuilder.Entity("Project.Models.MediaContent", b =>
                {
                    b.Navigation("AudioOption")
                        .IsRequired();

                    b.Navigation("MediaContentStreamingServices");

                    b.Navigation("Reviews");

                    b.Navigation("StreamingServices");

                    b.Navigation("SubtitleOption")
                        .IsRequired();

                    b.Navigation("WatchHistories");
                });

            modelBuilder.Entity("Project.Models.StreamingService", b =>
                {
                    b.Navigation("MediaContentStreamingServices");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Project.Models.Subscription", b =>
                {
                    b.Navigation("Confirmations");
                });

            modelBuilder.Entity("Project.Models.SubtitleOption", b =>
                {
                    b.Navigation("SubtitleLanguages");
                });

            modelBuilder.Entity("Project.Models.User", b =>
                {
                    b.Navigation("Confirmations");

                    b.Navigation("Reviews");

                    b.Navigation("WatchHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
